---
:verbose: true
:pidfile: tmp/pids/sidekiq.pid
:global: true
:concurrency: 3

:queues:
  - [deletegenotype, 10]
  - [zipgenotyping,5]
  - [zipfulldata,5]
  - [recommend,5]
  - [fitbit,3]
  - [frequency,1]
  - [fixphenotypes,1]
  - [default, 1]
  - [mailnewgenotype, 10]
  - [mailers, 1]
  - [user_snps, 3]
  - [preparse,3]
  - [parse,3]
  - [mendeley_details,1]
  - [mendeley,1]
  - [genomegov,1]
  - [pgp,1]
  - [plos_details,1]
  - [plos,1]
  - [snpedia,1]
:limits:
  recommend: 1
  zipgenotyping: 1
  zipfulldata: 1
  fitbit: 3
  frequency: 10
  fixphenotypes: 1
  mailnewgenotype: 1
  user_snps: 1
  preparse: 2
  parse: 1
  genomegov: 1
  mendeley_details: 1
  mendeley: 1
  pgp: 1
  plos_details: 1
  plos: 1
  snpedia: 1
